main:

- name: method
  label: Method
  type: stacked
  default: "sample"
  options: "image features,sample,prediction score,velocity"

  sample:
    - name: per_video
      label: Samples Per Video
      type: int
      default: 50
      range: 1,3000
    - name: sampling_method
      label: Sampling method
      type: list
      options: random,stride
      default: stride

  "image features":
    - name: per_video
      label: Initial Samples Per Video
      type: int
      default: 200
      range: 1,3000
    - name: sample_method
      label: Sampling method
      type: list
      options: random,stride
      default: stride
    - name: scale
      label: Image Scale
      type: double
      default: 1.0
    - name: merge_video_features
      label: Compute Features
      type: list
      options: per video,across all videos
      default: per video
    - name: feature_type
      label: Image Feature Type
      type: list
      options: raw images,brisk,hog
      default: raw images
    - name: brisk_threshold
      label: Brisk Keypoint Threshold
      type: int
      default: 40
    - name: vocab_size
      label: Bag of Features Vocab Size
      type: int
      default: 20
    - name: pca_components
      label: PCA Components
      type: int
      default: 5
    - name: n_clusters
      label: K-Means Clusters
      type: int
      default: 5
    - name: per_cluster
      label: Samples Per Cluster
      type: int
      default: 5


  strides:

  - name: per_video
    label: Suggestions per video
    type: int
    default: 10
    range: 1,1000

  random:

  - name: per_video
    label: Suggestions per video
    type: int
    default: 10
    range: 1,1000

  "prediction score":

  - name: score_limit
    label: Low score (lt)
    type: double
    default: 3.0
    range: 0,100
  - name: instance_limit
    label: Instance count (gte)
    type: int
    default: 2
    range: 1,10

  velocity:
  - name: node
    label: Node
    type: list
  - name: threshold
    label: Velocity Threshold
    type: double
    default: 0.1
    range: 0.1,1.0

- name: generate_button
  label: Generate Suggestions
  type: button
  default: main action